---
name: Labels

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  maintenance:
    name: Maintenance
    uses: fabasoad/reusable-workflows/.github/workflows/wf-sync-labels.yml@3ae541f80e3e6aca1f2c3705477fbef2890f1c98 # main
    permissions:
      contents: write
      issues: write
      pull-requests: write
